### ISSUE TITLE
Error sending metrics with DNS service discovery

### ISSUE THREAD

**Issue by bwmills** [Stackdriver/stackdriver-prometheus-sidecar#115]
### Issue

After updating a Prometheus stateful set manifest to support this sidecar, with debug logging enabled and a filter that sends metrics to Stackdriver for a Cassandra cluster only:

* No data has been sent to Stackdriver yet
* Sidecar debug logs shows: 
```
level=debug ts=2019-04-04T20:08:08.329734376Z caller=series_cache.go:361 component="Prometheus reader" msg="unknown resource" labels="{instance=\"cassandra-0.cassandra-svc.staging.svc.cluster.local:7090\", job=\"cassandra\"}"
level=debug ts=2019-04-04T20:08:08.329734376Z caller=series_cache.go:361 component="Prometheus reader" msg="unknown resource" labels="{instance=\"cassandra-1.cassandra-svc.staging.svc.cluster.local:7090\", job=\"cassandra\"}"
level=debug ts=2019-04-04T20:08:08.329734376Z caller=series_cache.go:361 component="Prometheus reader" msg="unknown resource" labels="{instance=\"cassandra-2.cassandra-svc.staging.svc.cluster.local:7090\", job=\"cassandra\"}"
...
level=info ts=2019-04-04T22:16:58.428704742Z caller=manager.go:211 component="Prometheus reader" msg="reached first record after start offset" start_offset=101889806 skipped_records=228926
```

### Environment, Images and Names

* Environment: `GKE`
* Prometheus image: `2.6.1`
* stackdriver-prometheus-sidecar image: `0.4.1`
* Prometheus stateful set name: `prometheus-dev` (one replica only)
* Pod name: `prometheus-dev-0`

> The Kubernetes cluster has Stackdriver Kubernetes Monitoring (beta) enabled.

### Prometheus Stateful Set Manifest
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prometheus-dev
  name: prometheus-dev
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-dev
  serviceName: prometheus-dev-lb
  template:
    metadata:
      labels:
        app: prometheus-dev
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - prometheus-dev
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - prometheus-dev
              topologyKey: kubernetes.io/hostname
            weight: 50
      containers:
      - args:
        - --stackdriver.project-id=<redacted>
        - --prometheus.wal-directory=/prometheus/wal
        - --prometheus.api-address=http://127.0.0.1:9090/
        - --stackdriver.kubernetes.location=us-central1
        - --stackdriver.kubernetes.cluster-name=<redacted>
        - --filter=job="cassandra"
        - --log.level=debug
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.4.1
        imagePullPolicy: Always
        name: sidecar
        ports:
        - containerPort: 9091
          name: sidecar
          protocol: TCP
        volumeMounts:
        - mountPath: /prometheus
          name: datadir
      - image: prom/prometheus:v2.6.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 35
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 9090
          timeoutSeconds: 5
        name: prometheus
        ports:
        - containerPort: 9090
          name: web-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9090
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /prometheus
          name: datadir
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config-file
          subPath: prometheus.yml
      nodeSelector:
        pool: mon
      restartPolicy: Always
      securityContext:
        fsGroup: 99
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: pool
        operator: Equal
        value: mon
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-config
        name: prometheus-config-file
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: ssd
```

### Prometheus scrape config
```
      - job_name: cassandra

        scrape_interval: 15s
        scrape_timeout: 10s

        dns_sd_configs:
        - names:
          - _prometheus-jmx._tcp.cassandra-svc
```
### Logs

Looking at the sidecar log output, it looks good initially:
```
level=info ts=2019-04-04T18:17:33.260259902Z caller=main.go:256 msg="Starting Stackdriver Prometheus sidecar" version="(version=0.4.0, branch=master, revision=3c176b3f5c58e85645e598de5b82f95dca814497)"
level=info ts=2019-04-04T18:17:33.260731139Z caller=main.go:257 build_context="(go=go1.12, user=kbuilder@kokoro-gcp-ubuntu-prod-283836442, date=20190325-14:24:29)"
level=info ts=2019-04-04T18:17:33.260857444Z caller=main.go:258 host_details="(Linux 4.14.65+ #1 SMP Sun Sep 9 02:18:33 PDT 2018 x86_64 prometheus-dev-0 (none))"
level=info ts=2019-04-04T18:17:33.260995428Z caller=main.go:259 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-04-04T18:17:33.265969971Z caller=main.go:463 msg="Web server started"
level=info ts=2019-04-04T18:17:33.277646916Z caller=main.go:444 msg="Stackdriver client started"
```
but then once Prometheus scrapes and the sidecar attempts to operate (as noted above), there are multiple instances of this `unknown resource` message (for each cassandra node):
```
level=debug ts=2019-04-04T20:43:05.287691058Z caller=series_cache.go:361 component="Prometheus reader" msg="unknown resource" labels="{instance=\"cassandra-2.cassandra-svc.staging.svc.cluster.local:7090\", job=\"cassandra\"}"
```
### Notes

* The `cassandra` job is good and all Cassandra pods are `UP` in Prometheus
* Expected metrics being exported from Cassandra are present in Prometheus
* In Prometheus UI, as an example Cassandra `Label`:
```
instance="cassandra-2.cassandra-svc.staging.svc.cluster.local:7090" job="cassandra"
```

### Questions

**(1) Filtering documentation**

Per the readme, I originally attempted to use:
```
--filter='job="cassandra"'
```
But that caused:
```
level=error ts=2019-04-04T18:48:53.374995353Z caller=main.go:291 msg="Error parsing filters" err="invalid filter \"'job=\\\"cassandra\\\"'\""
```
I now have:
```
--filter=job="cassandra"
```
which appears to be ok - is this a documentation bug in your readme?

**(2) Shared volume**

We store Prometheus data in a a persistent volume:
```
        volumeMounts:
        - mountPath: /prometheus
          name: datadir
```
```
 volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: ssd
```

And so for the sidecar, added:
```
       volumeMounts:
        - mountPath: /prometheus
          name: datadir
```
Does this setup look right? I assume so as the logs didn't complain but wanted to make sure things were good as far as sidecar requirements for writing to a shared volume, as noted [here](https://cloud.google.com/monitoring/kubernetes-engine/prometheus).

**(3) Getting data into Stackdriver**

Guessing the `unknown resource` log messages noted already are the reason that no data is getting sent by the sidecar to Stackdriver. Any help is much appreciated.

**Comment by jkohen** [comment]
Hi, thanks for the report. (3) is indeed pointing at the problem, and the cause is that using the DNS service discovery requires manual work on your part. Currently Stackdriver only officially supports the Kubernetes service discovery mechanism. I'll share the instructions with you, in case it helps.

You have to make sure that the metrics coming out from the "cassandra" scrape job have all the Stackdriver MonitoredResource labels set. You can see in the [k8s_container map](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/master/retrieval/resource_map.go#L94-L102) how the sidecar does this for you automatically when you are using Kubernetes service discovery. The metric label names you need to provide are on the right side of the map; the values need to match the value of the Prometheus labels on the left side of the map.

I hope that helps.

**Comment by bwmills** [comment]
@jkohen - thanks for the fast response - will test soon and follow-up here.
Also, for question (1), is my current filter syntax correct? Thanks.

**Comment by jkohen** [comment]
I think so. Quoting is tricky. The documentation shows the escaping needed on the command-line. You don't need it in YAML. I'll clarify, thanks for the feedback. And regarding (2), it looks fine to me, and (3) is definitely the issue here.

**Comment by bwmills** [comment]
@jkohen - I am closer thanks to your assistance and have tested a new Prometheus scrape config, though my targets are getting dropped during service discovery.

### New Prometheus Scrape Config
```
        # Config for delivery to Stackdriver by sidecar
      - job_name: infra-pods

        scrape_interval: 15s
        scrape_timeout: 10s

        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
```
The scrape config above is renamed from `cassandra` to `infra-pods` as we have additional infra applications that we want to support with respect to using this sidecar to ship metrics to Stackdriver. I will continue using Cassandra as the example infra application in this thread though.

Also above, I've changed from `dns_sd_configs` to ` kubernetes_sd_configs` (which I'm pretty sure is right), added `role: pod` and used the recommended config from [here](https://github.com/prometheus/prometheus/blob/release-2.8/documentation/examples/prometheus-kubernetes.yml) to relabel. 

#### Prometheus annotations in Cassandra stateful set manifest
```
    metadata:
      annotations:
        prometheus.io/port: "7090"
        prometheus.io/scrape: "true"
```

#### Updated filter for the sidecar
```
--filter=job="infra-pods"
```

Results from this setup are:

**(1) Sidecar Logs**
```
level=info ts=2019-04-05T16:52:57.088393717Z caller=main.go:256 msg="Starting Stackdriver Prometheus sidecar" version="(version=0.4.0, branch=master, revision=3c176b3f5c58e85645e598de5b82f95dca814497)"
level=info ts=2019-04-05T16:52:57.088789674Z caller=main.go:257 build_context="(go=go1.12, user=kbuilder@kokoro-gcp-ubuntu-prod-283836442, date=20190325-14:24:29)"
level=info ts=2019-04-05T16:52:57.08898269Z caller=main.go:258 host_details="(Linux 4.14.65+ #1 SMP Sun Sep 9 02:18:33 PDT 2018 x86_64 prometheus-dev-0 (none))"
level=info ts=2019-04-05T16:52:57.089116589Z caller=main.go:259 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-04-05T16:52:57.093275893Z caller=main.go:463 msg="Web server started"
level=info ts=2019-04-05T16:52:57.100008376Z caller=main.go:444 msg="Stackdriver client started"
level=warn ts=2019-04-05T16:53:00.140773948Z caller=main.go:525 msg="Prometheus not ready" status="503 Service Unavailable"

level=info ts=2019-04-05T16:54:03.101683018Z caller=manager.go:150 component="Prometheus reader" msg="Starting Prometheus reader..."
level=info ts=2019-04-05T16:54:06.689099395Z caller=manager.go:211 component="Prometheus reader" msg="reached first record after start offset" start_offset=255876184 skipped_records=446286
```
^ nothing really .. and more importantly:

**(2) Prometheus Service Discovery**

Prometheus UI - `Status - Service Discovery` shows that all my `infra-pods` are being dropped. I read somewhere that:

> Any labels starting with `__meta` in Prometheus are automatically dropped unless they are relabeled to a different value ...

Which may be relevant, though I suspect that I haven't quite followed your instructions properly regarding the link you provided to `k8s_container map` and the LabelMap there. 

### Question

Do I need to keep the relabel config I have for the scrape and port annotations and add additional `source_labels:`? Or are my existing `source_labels:` unnecessary per the sidecar + Stackdriver requirements?

**Comment by jkohen** [comment]
@bwmills I think the issue is minor, you have to change `__meta_kubernetes_service_annotation_prometheus_io_scrape` to `__meta_kubernetes_pod_annotation_prometheus_io_scrape` and `__meta_kubernetes_service_annotation_prometheus_io_port` to `__meta_kubernetes_pod_annotation_prometheus_io_port`, because you are using `role: pod` instead of `role: service`.

Let me know if that helps.

**Comment by bwmills** [comment]
@jkohen - many thanks once again (how did I miss that).

Confirmed: 

* This last change has resolved the dropped targets in Prometheus
* Data is now available in Stackdriver

For anyone who might benefit from this thread:

### Final Prometheus Scrape Config
```
# Config for delivery to Stackdriver by sidecar
- job_name: infra-pods

scrape_interval: 15s
scrape_timeout: 10s

kubernetes_sd_configs:
- role: pod

relabel_configs:
- source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
  action: keep
  regex: true
- source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
  action: replace
  target_label: __address__
  regex: ([^:]+)(?::\d+)?;(\d+)
  replacement: $1:$2
```

Issue is resolved.
