### ISSUE TITLE
Getting Counters into SD

### ISSUE THREAD

**Issue by bill-within** [Stackdriver/stackdriver-prometheus-sidecar#144]
Hi,
Is it possible to get Counter-type metrics into SD, high-cardinality or not? I see the Cumulative aggregator, and I could manually create one for each of my individual counters, but that's not exactly ideal. 

Prometheus has a Counter:
https://prometheus.io/docs/concepts/metric_types/

StackDriver has the same concept only they call it Cumulative:
https://cloud.google.com/monitoring/api/v3/metrics-details#metric-kinds

& I'd like to just map them 1-to-1 without having to update the stackdriver-prometheus-sidecar config every time I add a new one. I've been using Gauges for everything instead, but that feels a little dirty.

Thanks!

**Comment by jkohen** [comment]
@bill-within counter metrics are supported out of the box. Are you having any issues with that?

The aggregator feature is only intended to reduce cardinality.

**Comment by bill-within** [comment]
@jkohen I am, when I define something as a counter, Prometheus will pick it up OK (adding _total and _created), but it's never visible in Stackdriver. Any Gauges I create come through just fine, however.

**Comment by bill-within** [comment]
& no errors/warnings in the prom or sidecar logs

**Comment by jkohen** [comment]
Can you share your Prometheus and sidecar configurations? It would be useful to see the `/metrics` page for the metrics that aren't making it to Stackdriver.

Assigning to @bmoyles0117 after initial triage.

**Comment by bill-within** [comment]
You bet!

Relevant config snippet:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-configmap
  namespace: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
...
      - job_name: 'apps'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - dev
              - test
              - sand
        relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_pod_container_name]
          regex: (example-service1)
        - action: keep
          source_labels: [__meta_kubernetes_pod_container_port_name]
          regex: (metrics)
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - action: replace
          source_labels: [__meta_kubernetes_pod_name]
          target_label: pod_name
```

Deployment args:

```
      - name: prometheus
        image: gcr.io/xxx/prometheus:v2.11.1
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/
          - name: prometheus-storage-volume
            mountPath: /prometheus/
        args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus/
...
      - name: sidecar
        image: gcr.io/xxx/stackdriver-prometheus-sidecar:0.4.3
        imagePullPolicy: Always
        args:
          - "--stackdriver.project-id=xxx"
          - "--prometheus.wal-directory=/prometheus/wal"
          - "--stackdriver.kubernetes.location=us-west2"
          - "--stackdriver.kubernetes.cluster-name=k8s-dev-1"
```

/metrics page snippet:

```
....
# HELP time_service_calls_total Number of calls to the backend time service
# TYPE time_service_calls_total counter
time_service_calls_total 48.0
# TYPE time_service_calls_created gauge
time_service_calls_created 1.5651240328555365e+09
```

Metric created in app via:

```
from prometheus_client import start_http_server, Counter
...
BACKEND_CALLS = Counter('time_service_calls', 'Number of calls to the backend time service')
```

Visible in Prometheus if I query 'time_service_calls_total':

```
Element 
time_service_calls_total{app="example-service1",instance="10.52.0.57:9090",job="apps",namespace="dev",pod_name="example-service1-579b595567-scpvp",pod_template_hash="579b595567"} 

Value
48
```
