### ISSUE TITLE
Uploading GB of metrics in short time

### ISSUE THREAD

**Issue by chmking** [Stackdriver/stackdriver-prometheus-sidecar#148]
Before we begin, it is important to note that I made this attempt after what I had come to know as Stackdriver Monitoring had become Legacy Stackdriver without being aware. 

In retrospect, I realize I may have too quickly skimmed the instructions that clearly said:
> You cannot configure clusters using Legacy Stackdriver with Prometheus.

I assumed, in error, that I did have Stackdriver Kubernetes Engine Monitoring enabled in my GKE cluster when I went about following the instructions here: https://cloud.google.com/monitoring/kubernetes-engine/prometheus

Additionally, I took a chance to see if I could get stackdriver-prometheus-sidecar working with our deployment of [prometheus-operator](https://github.com/coreos/prometheus-operator/tree/v0.29.0) version 0.29.0. Specifically, I deployed the Helm [chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) version 5.7.0. This deploys with prometheus version 2.9.1 which isn't listed in the compatibility matrix.

This was the container template:
```
      containers:
      - name: sidecar
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:{{ .Values.sidecar.tag }}
        args:
        - "--stackdriver.project-id={{ .Values.cluster.project }}"
        - "--prometheus.wal-directory=/prometheus/wal"
        - "--stackdriver.kubernetes.location={{ .Values.cluster.region }}"
        - "--stackdriver.kubernetes.cluster-name={{ .Values.cluster.name }}"
        ports:
        - name: sidecar
          containerPort: 9091
        volumeMounts:
        - name: prometheus-prometheus-operator-prometheus-db
          mountPath: /prometheus
```

Despite all of this, I was able to get prometheus-operator configured to deploy the stackdriver-prometheus-sidecar with prometheus deploys. These deploys were sending collected metrics to Stackdriver as expected. They were clearly showing up in the Stackdriver Metrics Explorer and I assumed all was well.

It is important to note that this is a small cluster which reports very little in the way of metrics and only a small group of custom metrics.

![metrics](https://user-images.githubusercontent.com/12450799/62954972-83382f00-bdad-11e9-8a93-f74866c1e9d9.png)

I was surprised to find when I went to check the billing that it had uploaded almost 10 GB of metrics in such a short time.

I was hoping it might be clear what the root cause is.
- Is it because it was running on Stackdriver Legacy?
- Is it because of an incompatible version or Prometheus?
- Is it because of the Prometheus configuration?

Thanks for your time.
