### ISSUE TITLE
Autodetect GKE resource attributes

### ISSUE THREAD

**Issue by ocervell** [Stackdriver/stackdriver-prometheus-sidecar#250]
I'd like to deploy the SD prometheus sidecar without having to patch (i.e: just one YAML). 

Ideally it would look like this:
```
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.6.0
        imagePullPolicy: Always
        args:
        - "--config.file=/etc/prometheus/config/prometheus.yaml"
        - "--storage.tsdb.path=/data"
        - "--storage.tsdb.min-block-duration=15m"
        - "--storage.tsdb.max-block-duration=4h"
        - "--storage.tsdb.retention=48h"
        ports:
        - name: prometheus
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/config
        - name: data-volume
          mountPath: /data

      - name: stackdriver-prometheus-sidecar
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.7.5
        imagePullPolicy: Always
        args:
        - "--stackdriver.project-id=${GCP_PROJECT}"  # autodetect GCP project
        - "--prometheus.wal-directory=${DATA_DIR}/wal"
        - "--stackdriver.kubernetes.location=${GCP_REGION}" # autodetect GCP region
        - "--stackdriver.kubernetes.cluster-name=${KUBE_CLUSTER}" # autodetect GKE cluster name
        ports:
        - name: sidecar
          containerPort: 9091
        volumeMounts:
        - name: ${DATA_VOLUME}
          mountPath: ${DATA_DIR}
```

Any idea if we could have autodetected defaults for the arguments `--stackdriver.project_id`, `--stackdriver.kubernetes.location` and `--stackdriver.kubernetes.cluster-name` ? They would default to the GKE cluster they are running on.
